.TH UNIONFS 4
.SH NAME
unionfs \- union file server
.SH SYNOPSIS
.B unionfs
[
.B -D
] [
.B -abC
] [
.B -M
|
.B -m
.I mtpt
] [
.B -s
.I srvname
] [ [
.B -c
]
.I path ....
]
.SH DESCRIPTION
.PP
.I Unionfs
serves a file tree that represents a deep
merge of the file trees given by one or
more of the
.I path
arguments - unlike the namespace
operators described in
.IR bind (2),
which merge directory contents on
a single level.
.PP
If the
.I -c
flag is prefixed to a
.I path
it will be marked as a target for file
creation; otherwise the first path in the
list will be used. 
.PP
The command line options are:
.TF "-s srvname"
.TP
.B -D
Enable 9P trace output.
.TP
.BI -s \ srvname
Post channel on
.RI /srv/ srvname .
.TP
.BI -m \ mtpt
Set mountpoint
.RI ( /mnt/union
by default.)
.TP
.B -a, -b, -C
Work as described in
.IR bind (1).
.PD
.SH EXAMPLES
.EX
% unionfs -m /bin /rc/bin /arm/bin -c $home/bin/^(rc arm)
.EE
.SH SEE ALSO
.IR bind (1),
.IR bind (2)
.SH SOURCE
.B https://bitbucket.org/k-vik/unionfs
.SH BUGS
.PP
You're.
